### ISSUE TITLE
Broken file paths when build via GitHub Actions

### ISSUE THREAD

**Issue by koshikishi** [Ulyanov-programmer/gulp-sharp-optimize-images#2]
## Description
Hello.

When I automatically built and deploy my project on GitHub Pages using GitHub Actions ([github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action)), I discovered that this library was generating incorrect file paths for images. The generated paths contained an escaped backslash as a separator between the filename and base path, which seems to be handled incorrectly on Linux. This results in filenames being generated _with_ the base path included (see screenshot).

## Screenshots
![github](https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/assets/48867587/d555947f-17d2-4915-98eb-0cef222007bb)

## Files
* Workflow: https://github.com/koshikishi/koshikishi.github.io/blob/main/.github/workflows/gh-pages.yml

## Comments
I suspect the culprit might be [line 103](https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/blob/116c7412ca4b40ac603b3609d9fd96fbe002aca6/index.js#L103), where the full file path is being created. Perhaps the fix could be as simple as replacing the escaped backslash with a single slash (/). Though I don't know for sure :)
```javascript
let newFilePath = `${file.dirname}/${newFileName}`
```

**Comment by Ulyanov-programmer** [comment]
That's right, apparently, the problem is the different perception of file paths on these OS. 
I made some changes (https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/commit/4c28c1ec16e36347070744fdefc8baa76cd1ab8e), try cloning the version from github and try again.

Just add in your package.json this:
`"gulp-sharp-optimize-images": "github:Ulyanov-programmer/gulp-sharp-optimize-images#master",`
And start the reassembly of packages.

**Comment by koshikishi** [comment]
Yes, I just tested this on a private clone of my project and it worked correctly. Great, thanks!

**Comment by xdevelx** [comment]
Same problem with the directory name in the filename. Maybe you should use https://nodejs.org/api/path.html instead of parsing paths with string methods?

![Screenshot_20240422_134042](https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/assets/16085855/abc9479b-e313-441e-a3f2-a33450c425f1)

Version: 4.0.2

**Comment by Ulyanov-programmer** [comment]
Oops, I already forgot about this problem. I put a double slash again instead of a single slash. ¯ \ _ (ツ) _ / ¯
I made [changes](https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/commit/32fa513096d2a64ee9faee4618bde6d62bd8dde5) that should fix this problem once and for all (I used the `path.join` function), I ask you to try these changes on your machine by following the instructions above in the comments.

**Comment by xdevelx** [comment]
> I made [changes](https://github.com/Ulyanov-programmer/gulp-sharp-optimize-images/commit/32fa513096d2a64ee9faee4618bde6d62bd8dde5) that should fix this problem once and for all (I used the `path.join` function), I ask you to try these changes on your machine by following the instructions above in the comments.

The code from the master branch generates normal paths.

**Comment by Ulyanov-programmer** [comment]
> The code from the master branch generates normal paths.

This may seem rude, but in my work I have come across different people who explain the same thing with different answers. I have to ask again - is everything working correctly, as you expect?

**Comment by xdevelx** [comment]
> I have to ask again - is everything working correctly, as you expect?

Yes, the plugin is now working correctly and as expected.
